version: '3.4'
services:
  opencl:
    container_name: felix-opencl-container
    build: .
    volumes:
      - "${dirname $SSH_AUTH_SOCK}:${dirname $SSH_AUTH_SOCK}"
    environment:
      SSH_AUTH_SOCK: $$SSH_AUTH_SOCK

